services:
  kgup-tahmin-raporlari:
    image: wattica06/kgup-tahmin-raporlari:latest
    container_name: kgup_tahmin_raporlari
    restart: unless-stopped
    volumes:
      - /home/ubuntu/git/wattica-sisecam_enerji-platform/initial/seed/downloads/reports/prediction_reports/daily:/data/prediction_reports/sisecam/daily:ro
    env_file:
      - .env
    networks:
      - met-network

networks:
  met-network:
    external: true
